import re
from typing import List, Tuple
from .base_parser import BaseCodeParser

class JavaCodeParser(BaseCodeParser):
    """Parser for Java code generated by LLM."""
    
    def __init__(self):
        super().__init__()
        self.import_pattern = re.compile(r'^import\s+([^;]+);$', re.MULTILINE)
        self.package_pattern = re.compile(r'^package\s+([^;]+);$', re.MULTILINE)
        self.class_pattern = re.compile(r'^public\s+class\s+(\w+)\s*{', re.MULTILINE)

    def _extract_code_parts(self, code: str) -> Tuple[List[str], str]:
        """
        Extract imports and main code from Java code.
        
        Args:
            code: The complete Java code string
            
        Returns:
            Tuple[List[str], str]: List of imports and main code
        """
        # Extract imports
        imports = self.import_pattern.findall(code)
        
        # Validate imports
        self._validate_imports(imports)
        
        # Extract main code (everything after imports)
        main_code = self._extract_main_code(code)
        
        # Validate class structure
        self._validate_class_structure(main_code)
        
        return imports, main_code

    def _validate_imports(self, imports: List[str]) -> None:
        """
        Validate Java imports.
        
        Args:
            imports: List of import statements
            
        Raises:
            ValueError: If imports are invalid
        """
        for imp in imports:
            if not re.match(r'^[a-zA-Z][a-zA-Z0-9_.]*$', imp):
                raise ValueError(f"Invalid import statement: {imp}")

    def _extract_main_code(self, code: str) -> str:
        """
        Extract main code after imports.
        
        Args:
            code: Complete code string
            
        Returns:
            str: Main code without imports
        """
        # Find the last import statement
        last_import = 0
        for match in self.import_pattern.finditer(code):
            last_import = match.end()
        
        # Return everything after the last import
        return code[last_import:].strip()

    def _validate_class_structure(self, code: str) -> None:
        """
        Validate Java class structure.
        
        Args:
            code: Main code string
            
        Raises:
            ValueError: If class structure is invalid
        """
        # Check for class declaration
        class_match = self.class_pattern.search(code)
        if not class_match:
            raise ValueError("No public class declaration found")
        
        # Check for matching braces
        brace_count = 0
        for char in code:
            if char == '{':
                brace_count += 1
            elif char == '}':
                brace_count -= 1
                if brace_count < 0:
                    raise ValueError("Unmatched closing brace")
        
        if brace_count != 0:
            raise ValueError("Unmatched opening brace") 